# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0002_auto_20160601_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default=b'profile_pictures/user.png', upload_to=b'profile_pictures/'),
        ),
    ]
