# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-18 00:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0007_auto_20160616_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='hash',
            field=models.CharField(db_index=True, default='1234', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='milestone',
            name='deadline',
            field=models.DateField(default=datetime.date(2016, 6, 28), verbose_name='deadline'),
        ),
    ]
