# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0010_remove_annotation_aspect_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='json_value',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
    ]
