# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0013_auto_20160710_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_project.Comment'),
        ),
    ]
