# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0014_auto_20160710_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='annotation',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
    ]
