# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-06 00:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0015_auto_20160710_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='deadline',
            field=models.DateField(default=datetime.date(2016, 8, 16), verbose_name='deadline'),
        ),
    ]
