# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_project', '0016_auto_20160806_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_project.Project', verbose_name='project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='milestone',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='author',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='milestone',
        ),
        migrations.AddField(
            model_name='task',
            name='end',
            field=models.DateField(blank=True, help_text=b'YYYY-MM-DD', null=True, verbose_name='end'),
        ),
        migrations.AddField(
            model_name='task',
            name='end_is_milestone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='short_name',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.DateField(blank=True, help_text=b'YYYY-MM-DD', null=True, verbose_name='start'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_is_milestone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default=b'STATUS_ACTIVE', max_length=256),
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.AddField(
            model_name='resource',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_project.Task'),
        ),
        migrations.AddField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
