# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-11 08:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_project', '0017_auto_20160810_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedResource_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effort', models.BigIntegerField(null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_project.Role')),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='task',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='can_write',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='collapsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='depends',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='has_child',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.AddField(
            model_name='assignedresource_relation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_project.Task'),
        ),
        migrations.AddField(
            model_name='assignedresource_relation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
