# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-21 02:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0019_auto_20160818_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='deadline',
            field=models.DateField(default=datetime.date(2016, 8, 31), verbose_name='deadline'),
        ),
    ]
